### ISSUE TITLE
Shouldn't this project distributed as a module?

### ISSUE THREAD

**Issue by rafaelcn** [romana/rlog#25]
Since 1.14 (some time ago) we got go modules. If one, in the present day, executes a `go get` on your repo, expecting it to execute the example.go file in the `$GOPATH/pkg/mod/...` it won't work as it complains about no go.mod file. How do you feel about adding that?

**Comment by rafaelcn** [comment]
I could do it myself if you allow me :-)

**Comment by jbrendel** [comment]
Hello!

On Mon, 2022-04-11 at 14:53 -0700, Rafael C. Nunes wrote:
> I could do it myself if you allow me :-)

Yes, by all means, please add the file. Thank you!

**Comment by rafaelcn** [comment]
okay, @jbrendel I opened #26 to fix that.
